-- DSLQ RU App Supabase schema
-- Run in Supabase SQL Editor before connecting the deployed Streamlit app.

create table if not exists public.dslq_ru_sessions (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  session_id text not null,
  app_version text,
  dslq_chronic_score numeric,
  interpretation_band text,
  health_flag text,
  visual_scale_pos numeric,
  item_scores jsonb,
  behavior_answers jsonb,
  general_health_answers jsonb,
  research_choices jsonb,
  dog_demographics jsonb,
  consented_dog boolean not null default false
);

create index if not exists dslq_ru_sessions_session_id_idx
  on public.dslq_ru_sessions (session_id);

-- Optional RLS setup for Streamlit Community Cloud with anon key inserts.
-- Keep select/update/delete closed by default; allow insert only.
alter table public.dslq_ru_sessions enable row level security;

drop policy if exists "Allow public inserts into dslq_ru_sessions" on public.dslq_ru_sessions;
create policy "Allow public inserts into dslq_ru_sessions"
  on public.dslq_ru_sessions
  for insert
  to anon
  with check (true);
